### ISSUE TITLE
Known issue with API changing system (Work-around)

### ISSUE THREAD

**Issue by HarmlessTechnology** [HarmlessTechnology/APIWeather#2]
**Describe the bug**
This bug prevents the changing of the API correctly, causing an invalid API error.

**To Reproduce**
Try to use the GUI based API changer under options.

**Expected behavior**
API would change and provide weather data correctly.

**TEMPORARY WORK-AROUND**
Until the application is patched please do the following to add your API key:
-Go to the location of the application in file manager.
-Locate and open api_key.txt
-Remove any text or extra lines in the text file
-Paste your API key from openweathermap.org into this text file, ensuring it is on the first and only line.
-Open API Weather

This issue will be addressed in a future update.

**Comment by harmless7567** [comment]
This issue appears to be resolved upon the latest commit by changing the default api_key.txt file, please be sure to reinstall if using an older version. If you still encounter this bug please create a new issue.
